"""update job description model

Revision ID: 0133f9b2c163
Revises: 5c661b076c51
Create Date: 2026-05-07 15:00:55.188980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0133f9b2c163'
down_revision: Union[str, Sequence[str], None] = '5c661b076c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('preferred_skills', sa.Text(), nullable=True))
    op.add_column('job_descriptions', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('job_descriptions', sa.Column('experience_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'experience_years')
    op.drop_column('job_descriptions', 'experience')
    op.drop_column('job_descriptions', 'preferred_skills')
    # ### end Alembic commands ###
