"""make candidate_id unique in resumes

Revision ID: 6c4dc0fb53f6
Revises: 0133f9b2c163
Create Date: 2026-05-08 23:43:46.773213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4dc0fb53f6'
down_revision: Union[str, Sequence[str], None] = '0133f9b2c163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'resumes', ['candidate_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='unique')
    # ### end Alembic commands ###
