"""create candidate analysis table

Revision ID: a365b47d3a27
Revises: 6c4dc0fb53f6
Create Date: 2026-05-09 11:48:05.165506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a365b47d3a27'
down_revision: Union[str, Sequence[str], None] = '6c4dc0fb53f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_analysis_id'), table_name='candidate_analysis')
    op.drop_table('candidate_analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('analysis_result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('candidate_analysis_candidate_id_fkey')),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.id'], name=op.f('candidate_analysis_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('candidate_analysis_pkey'))
    )
    op.create_index(op.f('ix_candidate_analysis_id'), 'candidate_analysis', ['id'], unique=False)
    # ### end Alembic commands ###
